### ISSUE TITLE
R v>4 fails to run the broom package functions

### ISSUE THREAD

**Issue by RossDwyer** [seananderson/glmm-course#17]
Hi Sean,
Upon running your random-slopes and temporal-autocorrelation functions I discovered that the broom package throws an error which can be rectified by loading the library(broom.mixed) in its place.
Great course materials by the way, really helped with my analysis of temporally correlated fish movement dataset.
Cheers, 
Ross

**Comment by seananderson** [comment]
Thanks for pointing that out! Should be all fixed with this commit https://github.com/seananderson/glmm-course/commit/a24cb5d3de596c21334669cb1105d69e9a7f9d50
